### ISSUE TITLE
USER STORY: search for a product by name or description

### ISSUE THREAD

**Issue by evelynfoy** [evelynfoy/the-cheese-and-wine-boutique#14]
As a **Shopper** I can **search for a product by name or description**, so that **I can more easily find something more specific**

# Acceptance Criteria

* Acceptance Criteria 1: I can enter a search parameter
* Acceptance Criteria 2: The list of products displayed reflects the entry

# Tasks

- [ ] Add a search box to the base template
- [ ] Add functionality to search products on name or description
- [ ] Add functionality to filter products displayed based on results
