### ISSUE TITLE
USER STORY: Add products to a virtual shopping bag

### ISSUE THREAD

**Issue by evelynfoy** [evelynfoy/the-cheese-and-wine-boutique#21]
As a **shopper** I can **add products to a virtual shopping bag**, so that **I can purchase more than one item**

# Acceptance Criteria

* Acceptance Criteria 1: There is a button to add a product to a virtual shopping bag
* Acceptance Criteria 2: On clicking I receive confirmation that the product has been added.

# Tasks

- [ ] Add shopping bag app 
- [ ] Add shopping bag context functionality
- [ ] Add functionality to add product to context
