### ISSUE TITLE
USER STORY: Purchase a product securely

### ISSUE THREAD

**Issue by evelynfoy** [evelynfoy/the-cheese-and-wine-boutique#27]
As a **shopper** I can **purchase a product securely**, so that **I can get it sent out to me**

# Acceptance Criteria

* Acceptance Criteria 1: I can choose to purchase an item
* Acceptance Criteria 2: I can enter my card details
* Acceptance Criteria 3: I receive confirmation that my order has been completed.

# Tasks

- [ ] Add stripe elements to website
- [ ] Add stripe functionality to create payment intent
- [ ] Add checkout app and order models
