### ISSUE TITLE
USER STORY: Add a wine product

### ISSUE THREAD

**Issue by evelynfoy** [evelynfoy/the-cheese-and-wine-boutique#4]
As a **store owner** I can **add a wine product**, so that **I can sell it in my store**

# Acceptance Criteria

* Acceptance Criteria 1: There is an option on the website which allows me to add a wine product
* Acceptance Criteria 2: I can enter wine details 
* Acceptance Criteria 3: On submit the entry is saved to the database
* Acceptance Critieria 4: On submit I receive a success message informing me it has been added.

# Tasks

- [ ] Add wine model
- [ ] Add form to website
- [ ] Add feedback message
- [ ] Save details to database
