### ISSUE TITLE
USER STORY: View a specific category of product

### ISSUE THREAD

**Issue by evelynfoy** [evelynfoy/the-cheese-and-wine-boutique#53]
As a **shopper** I can **view a specific category of product**, so that **I can more easily see what's on offer**

# Acceptance Criteria

* Acceptance Criteria 1: I can select a particular category of product to view
* Acceptance Criteria 2: I can see the list filtered by my chosen category

# Tasks

- [ ] Add a dropdown filter control to the nav bar
- [ ] Add functionality to filter the product list by the selected value
- [ ] Return the filtered list for display
