### ISSUE TITLE
USER STORY: Edit a deal product

### ISSUE THREAD

**Issue by evelynfoy** [evelynfoy/the-cheese-and-wine-boutique#8]
As a **store owner** I can **edit  a cheese and wine deal product**, so that **I can update the details, price etc**

# Acceptance Criteria

* Acceptance Criteria 1: I can click an option to edit a deal product
* Acceptance Criteria 2: I can see the details for the product
* Acceptance Criteria 3: I can submit new details
* Acceptance Criteria 4: I can see the details have changed

# Tasks

- [ ] Populate form from database
- [ ] Save new values to database
- [ ] Send feedback message
